name: river_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  random_name_generator: ^1.1.0
  riverpod_annotation: ^2.1.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.5
  riverpod_lint: ^2.0.0

flutter:
  uses-material-design: true
